mybatis-plus:
  # ?????(???????????????????????????????????????????????)
  #  type-aliases-package: com.xxx.xxx.xxx.model.entity
  # xml????????????????(?? Mapper ???? XML ????)
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ??mybatisplus??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??????????????:???????Java???????????
    map-underscore-to-camel-case: true
    # ??????????????? MyBatis ???????????????
    # ???resultType="map"???null?
    call-setters-on-nulls: true
    # ?????????sql?????????????????(??????)
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # ???? AUTO:"???ID??"
      # INPUT:"????ID",
      # ID_WORKER:"????ID (??????ID)",
      # UUID:"????ID UUID";
      id-type: auto
      # ???? IGNORED:"????"  NOT_NULL:"? NULL ??")  NOT_EMPTY:"????"
      # ???
      logic-not-delete-value: 0
      # ???
      logic-delete-value: java.util.Date
      # ????????
#      table-prefix: t_